name: DEV CI/CD Workflow

on:
  push:
    branches:
      - develop1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        run: |
          cat /etc/os-release
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Log in to ECR
        run: 
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com
          
      - name: Create .env file
        run: |
         echo "REACT_APP_STAGING_URL=${{ secrets.REACT_APP_STAGING_URL }}" > .env
         echo "REACT_APP_VERIFIER_SERVICE_URL=${{ secrets.REACT_APP_VERIFIER_SERVICE_URL }}" >> .env
         echo "REACT_APP_WEB_SOCKET_SERVER=${{ secrets.REACT_APP_WEB_SOCKET_SERVER }}" >> .env
         echo "REACT_APP_ISSUER_SERVICE_URL=${{ secrets.REACT_APP_ISSUER_SERVICE_URL }}" >> .env
         echo "REACT_APP_PROOF_REQUEST_RESTRICTIONS_SCHEMAID=${{ secrets.REACT_APP_PROOF_REQUEST_RESTRICTIONS_SCHEMAID }}" >> .env
         echo "REACT_APP_ISSUE_CREDENTIAL_CREDDEFID=${{ secrets.REACT_APP_ISSUE_CREDENTIAL_CREDDEFID }}" >> .env
         echo "REACT_APP_SECRET_KEY=${{ secrets.REACT_APP_SECRET_KEY }}" >> .env
         echo "REACT_APP_CLIENT_ID=${{ secrets.REACT_APP_CLIENT_ID }}" >> .env
         echo "REACT_APP_SOCKET_NKEY_ID=${{ secrets.REACT_APP_SOCKET_NKEY_ID }}" >> .env
         echo "REACT_APP_PERMANENT_ADDRESS_SCHEMAID=${{ secrets.REACT_APP_PERMANENT_ADDRESS_SCHEMAID }}" >> .env
         echo "REACT_APP_EMPLOYMENT_SCHEMAID=${{ secrets.REACT_APP_EMPLOYMENT_SCHEMAID }}" >> .env
         echo "REACT_APP_ENCRYPTION_KEY=${{ secrets.REACT_APP_ENCRYPTION_KEY }}" >> .env
         echo "REACT_APP_ENCRYPTION_KEY=${{ secrets.REACT_APP_VIDEO_GUID_LINK }}" >> .env
         echo "REACT_APP_ENCRYPTION_KEY=${{ secrets.REACT_APP_BANK_ACCOUNT_SCHEMA_ID }}" >> .env
         echo "REACT_APP_EMPLOYMENT_RECORD_CRED_DEF_ID=${{ secrets.REACT_APP_EMPLOYMENT_RECORD_CRED_DEF_ID }}" >> .env
         echo "REACT_APP_VIDEO_GUID_LINK=${{ secrets.REACT_APP_VIDEO_GUID_LINK }}" >> .env

    
      - name: Copy Docker Compose file to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEV_INSTANCE_IP }}
          username: ${{ secrets.DEV_INSTANCE_USERNAME }}
          key: ${{ secrets.DEV_INSTANCE_PRIVATE_KEY }}
          passphrase: ${{ secrets.EC2_INSTANCE_PASSPHRASE }}
          source: docker-compose.yml
          target: /home/${{ secrets.DEV_INSTANCE_USERNAME }}/workspace/ndi-cloud-wallet-frontend
    
      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com/qacloudwalletservice:frontend .
          docker images
          ls -al
          cat .env

      - name: Push Docker image to AWS ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com/qacloudwalletservice:frontend

      
  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: SSH into EC2 instance and deploy Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_INSTANCE_IP }}
          username: ${{ secrets.DEV_INSTANCE_USERNAME }}
          key: ${{ secrets.DEV_INSTANCE_PRIVATE_KEY }}
          passphrase: ${{ secrets.EC2_INSTANCE_PASSPHRASE }}
          script: |
            cd /home/${{ secrets.DEV_INSTANCE_USERNAME }}/workspace/ndi-cloud-wallet-frontend
            # Check if the container exists
            aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 589943763826.dkr.ecr.ap-southeast-1.amazonaws.com
            docker-compose pull ndi-cloud-wallet-frontend
            docker-compose up -d ndi-cloud-wallet-frontend
             # Remove dangling images (if any)
            if [ -n "$(docker images -f 'dangling=true' -q)" ]; then
            docker rmi $(docker images -f "dangling=true" -q) || true  # Ignore errors if images are in use
            fi
             
             